databases:
  - name: budget_database
    databaseName: budget_database_ghwu
    user: budget_database_ghwu_user

services:
  - type: web
    name: budget-app
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: budget_database_ghwu
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false